### ISSUE TITLE
Build Galera Cluster with openssl instead of yassl

### ISSUE THREAD

**Issue by shinguz** [mariadb-corporation/mysql-wsrep#121]
Galera Cluster packages built by Codership contains yassl. Customer would like to have openssl instead.

Percona and MariaDB and MySQL Enterprise all use OpenSSL instead. Only MySQL Community uses the less powerful/feature complete YaSSL

**Comment by ayurchen** [comment]
For example for RPM builds the following must be passed to `rpmbuild`: `--define='with_ssl system'`

**Comment by philip-galera** [comment]
This adds some overhead because we need to track OpenSSL security vulnerabilities and release new packages when they happen ...

From a customer perspective, what is the difference between Galera with OpenSSL and Galera with YaSSL?

**Comment by ronin13** [comment]
Actually, it is the opposite, if there is a vulnerability with OpenSSL, you don't have to do anything unless the ABI changes. Users have to upgrade openssl on their box.

On the other hand, if there is a vulnerability in YaSSL, you will have to do a new release since it is statically built into mysqld.

Also, isn't galera library built with openssl? So, with mysqld + galera, you will be distributing   yassl and adding an additional requirement  of openssl for galera.

**Comment by philip-galera** [comment]
Pushed to master. The next Galera Cluster release will be built with OpenSSL on all platforms with the exception of the binary tarball, which will be yassl.
