### ISSUE TITLE
mysql-wsrep-5.5: Mysql service refuses to start on Ubuntu precise

### ISSUE THREAD

**Issue by philip-galera** [mariadb-corporation/mysql-wsrep#81]
The mysql service refuses to start because the pre-start script fails.

After installing logging, here is what happens:

```
+ sudo cat myjob.log
+ ERR_LOGGER=logger -p daemon.err -t /etc/init/mysql.conf -i
+ [ -r /etc/mysql/my.cnf ]
+ [ -d /var/run/mysqld ]
+ /lib/init/apparmor-profile-load usr.sbin.mysqld
AppArmor parser error for /etc/apparmor.d/usr.sbin.mysqld in /etc/apparmor.d/usr.sbin.mysqld at line 44: Could not open 'local/usr.sbin.mysqld'
```

So there is a problem with AppArmor.

**Comment by ottok** [comment]
The incude line `#include <local/usr.sbin.mysqld>` and in fact all of the debian/apparmor-profile file is identical for 5.5 and 5.6. I can't figure out the cause of your error message right now.

By the way, I wonder if apparmor profiles can work correctly or if they should be extended to allow some galera specific actions. In MariaDB apparmor profiles where removed because they introduced hard to debug errors by stopping the application from working normally in non-hostile situations. Maybe we should remove apparmor in mysql-wsrep too?

**Comment by philip-galera** [comment]
We already ask users to disable selinux and such before install Galera, so maybe we should remove apparmor altogether. Let me get Teemu's opinion on this.

**Comment by philip-galera** [comment]
We discussed this with Teemu. Lets remove the apparmor profiles in both 5.5 and 5.6 .

**Comment by ottok** [comment]
ok, I'll do that

**Comment by philip-galera** [comment]
Now works on Ubuntu Precise
